<?php

// GATE LABEL
$gate_label = [

    'CUT_TO_SM_SUBCONT' => 'Cut → SM',

    'SM_SUBCONT_FROM_CUT' => 'SM Incoming',
    'SM_SUBCONT_TO_WH_SUBCONT' => 'SM → WH',

    'WH_SUBCONT_FROM_SM_SUBCONT' => 'WH Incoming',
    'WH_SUBCONT_TO_VENDOR' => 'WH → Vendor',

    'VENDOR_FROM_WH_SUBCONT' => 'Vendor Incoming',
    'VENDOR_TO_WH_SUBCONT' => 'Vendor → WH',

    'WH_SUBCONT_FROM_VENDOR' => 'WH Return',
    'WH_SUBCONT_TO_SM_SUBCONT' => 'WH → SM',

    'SM_SUBCONT_FROM_WH_SUBCONT' => 'SM Return',
    'SM_SUBCONT_TO_NCVS' => 'SM → Production',
];


// MAPPING GATE
$next_gate_map = [

    'CUT_TO_SM_SUBCONT' => 'SM_SUBCONT_FROM_CUT',

    'SM_SUBCONT_FROM_CUT' => 'SM_SUBCONT_TO_WH_SUBCONT',
    'SM_SUBCONT_TO_WH_SUBCONT' => 'WH_SUBCONT_FROM_SM_SUBCONT',

    'WH_SUBCONT_FROM_SM_SUBCONT' => 'WH_SUBCONT_TO_VENDOR',
    'WH_SUBCONT_TO_VENDOR' => 'VENDOR_FROM_WH_SUBCONT',

    'VENDOR_FROM_WH_SUBCONT' => 'VENDOR_TO_WH_SUBCONT',
    'VENDOR_TO_WH_SUBCONT' => 'WH_SUBCONT_FROM_VENDOR',

    'WH_SUBCONT_FROM_VENDOR' => 'WH_SUBCONT_TO_SM_SUBCONT',
    'WH_SUBCONT_TO_SM_SUBCONT' => 'SM_SUBCONT_FROM_WH_SUBCONT',
    
    'SM_SUBCONT_FROM_WH_SUBCONT' => 'SM_SUBCONT_TO_NCVS',
];